// Auto-generated
let project = new Project('updog');

project.addSources('Sources');
project.addLibrary("F:/Program Files/Armory/armsdk//armory");
project.addLibrary("F:/Program Files/Armory/armsdk//iron");
project.addLibrary("F:/Program Files/Armory/armsdk//lib//haxebullet");
project.addAssets("F:/Program Files/Armory/armsdk//lib/haxebullet/js/ammo/ammo.js", { notinlist: true });
project.addParameter("--macro include('armory.trait')");
project.addParameter("--macro include('armory.trait.internal')");
project.addParameter("--macro include('armory.trait.physics')");
project.addParameter("--macro include('armory.trait.physics.bullet')");
project.addParameter("--macro include('armory.logicnode')");
project.addParameter('armory.trait.physics.bullet.RigidBody');
project.addParameter("--macro keep('armory.trait.physics.bullet.RigidBody')");
project.addParameter('arm.node.CorgiHop');
project.addParameter("--macro keep('arm.node.CorgiHop')");
project.addParameter('armory.trait.physics.bullet.PhysicsWorld');
project.addParameter("--macro keep('armory.trait.physics.bullet.PhysicsWorld')");
project.addShaders('K:/Animations/Updog/build_updog/compiled/Shaders/blur_shadow_pass.frag.glsl');
project.addShaders('K:/Animations/Updog/build_updog/compiled/Shaders/dilate_pass.frag.glsl');
project.addShaders('K:/Animations/Updog/build_updog/compiled/Shaders/pass.vert.glsl');
project.addShaders('K:/Animations/Updog/build_updog/compiled/Shaders/visibility_pass.frag.glsl');
project.addShaders('K:/Animations/Updog/build_updog/compiled/Shaders/visibility_pass.vert.glsl');
project.addShaders('K:/Animations/Updog/build_updog/compiled/Shaders/world_pass.frag.glsl');
project.addShaders('K:/Animations/Updog/build_updog/compiled/Shaders/world_pass.vert.glsl');
project.addShaders('build_updog/compiled/Shaders//Material_002_mesh.frag.glsl');
project.addShaders('build_updog/compiled/Shaders//Material_mesh.frag.glsl');
project.addShaders('build_updog/compiled/Shaders//Material_mesh.vert.glsl');
project.addShaders('build_updog/compiled/Shaders//Material_shadowmap.frag.glsl');
project.addShaders('build_updog/compiled/Shaders//Material_shadowmap.vert.glsl');
project.addAssets("build_updog/compiled/Shaders/Material_002_data.arm", { notinlist: true });
project.addAssets("build_updog/compiled/Shaders/Material_data.arm", { notinlist: true });
project.addAssets("build_updog/compiled/Shaders/shader_datas.arm", { notinlist: true });
project.addAssets("F:/Program Files/Armory/armsdk/armory/Assets/brdf.png", { notinlist: true });
project.addAssets("K:/Animations/Updog/build_updog/compiled/Assets/Scene.arm", { notinlist: true });
project.addAssets("K:/Animations/Updog/build_updog/compiled/Assets/meshes/action_CameraAction.arm", { notinlist: true });
project.addAssets("K:/Animations/Updog/build_updog/compiled/Assets/meshes/action_CorgiAction.arm", { notinlist: true });
project.addAssets("K:/Animations/Updog/build_updog/compiled/Assets/meshes/action_PlaneAction.arm", { notinlist: true });
project.addAssets("K:/Animations/Updog/build_updog/compiled/Assets/meshes/action_SunAction.arm", { notinlist: true });
project.addAssets("K:/Animations/Updog/build_updog/compiled/Assets/meshes/mesh_Cylinder.001.arm", { notinlist: true });
project.addAssets("K:/Animations/Updog/build_updog/compiled/Assets/meshes/mesh_Plane.arm", { notinlist: true });
project.addAssets("build_updog/compiled/Assets/envmaps/World_irradiance.arm", { notinlist: true });
project.addDefine('arm_ltc');
project.addDefine('rp_renderer=Forward');
project.addDefine('rp_shadowmap');
project.addDefine('rp_shadowmap_size=1024');
project.addDefine('rp_background=World');
project.addDefine('rp_gi=Off');
project.addDefine('rp_ssgi=Off');
project.addDefine('rp_soft_shadows');
project.addDefine('arm_physics');
project.addDefine('arm_bullet');
project.addDefine('arm_shaderload');
project.addDefine('arm_soundcompress');
project.addDefine('arm_fast');


resolve(project);
